### ISSUE TITLE
Cannot translate geoid files of unknown datum

### ISSUE THREAD

**Issue by busstoptaktik** [Kortforsyningen/kmsgrid#2]
As in:

```
λ kmsgrid translate -d GTX  -co epsg=4258 "c:\Program Files\Geoids2013\fehmarngeoid10.bin" fehmarngeoid10.gtx 1
Traceback (most recent call last):
  File "c:\users\b004330\appdata\local\continuum\anaconda3\envs\firedev\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\b004330\appdata\local\continuum\anaconda3\envs\firedev\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\B004330\AppData\Local\Continuum\anaconda3\envs\firedev\Scripts\kmsgrid.exe\__main__.py", line 9, in <module>
  File "c:\users\b004330\appdata\local\continuum\anaconda3\envs\firedev\lib\site-packages\kmsgrid.py", line 431, in main
    args.func(args)
  File "c:\users\b004330\appdata\local\continuum\anaconda3\envs\firedev\lib\site-packages\kmsgrid.py", line 354, in run_translate
    grid.export(args.out, args.dimensions, args.driver, args.creation_options)
  File "c:\users\b004330\appdata\local\continuum\anaconda3\envs\firedev\lib\site-packages\kmsgrid.py", line 321, in export
    srs.ImportFromEPSG(self.epsg)
  File "c:\users\b004330\appdata\local\continuum\anaconda3\envs\firedev\lib\site-packages\kmsgrid.py", line 261, in epsg
    raise ValueError('EPSG code not defined for datum "{0}"!'.format(self.datum))
ValueError: EPSG code not defined for datum "Fehmarn Datum 2010"!
```

**Comment by kbevers** [comment]
Pull requests are welcome :)

**Comment by rouault** [comment]
I was looking at the gaps of PROJ-data regarding EPSG records, and found one
INSERT INTO "grid_transformation" VALUES('EPSG','5626','FEH2010 to FCSVR10 height (1)','','EPSG','1047','Geographic3D to GravityRelatedHeight (Gravsoft)','EPSG','5592','EPSG','5597',0.1,'EPSG','8666','Geoid (height correction) model file','fehmarn_geoid10.gri',NULL,NULL,NULL,NULL,NULL,NULL,'FEM-Dnk-Deu Feh',0);
and Google pointed to you guys ;-)
Is this dataset public & open data licenses ? Pull requests to PROJ-data welcome ;-)

**Comment by kbevers** [comment]
It is at least public :-) The file is available for download [here](ftp://ftp.sdfe.dk/download/transformationsprogram/Geoids2013.zip) but I am not sure what the license status. We made the geoid grid back in the day on behalf of the Fehmarn belt company. It would be their responsibility to put the file under a suitable license. I'll contact some people and see what I can do.
